-- Q1. Display customer names along with their order details.
SELECT
    o.order_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    o.order_date,
    o.order_status,
    o.total_amount
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id;

-- Q2. Display products with their respective category names.
SELECT 
	p.product_name, 
    c.category_id, 
    p.brand, 
    p.price
FROM products p
INNER JOIN categories c
ON p.category_id = c.category_id;

-- Q3. Display products along with their seller details.
SELECT 
	p.product_name, 
    s.seller_id, 
    s.seller_name, 
    s.company_name, 
    s.email, 
    s.phone, 
    s.city, 
    s.state, 
    s.joining_date, 
    s.seller_rating
FROM products p
INNER JOIN sellers s
ON p.seller_id = s.seller_id;

-- Q4. Display complete order details with product information.
SELECT 
	o.order_item_id, 
    p.product_id, 
    o.quantity, 
	o.unit_price
FROM order_items o
INNER JOIN products p
ON o.product_id = p.product_id;

-- Q5. Display all customers and their orders, including customers without orders.
SELECT
	c.customer_id,
    CONCAT(c.first_name,' ',c.last_name),
    o.order_id,
    o.order_status
FROM customers c
LEFT JOIN orders o 
ON c.customer_id = o.customer_id;

-- Q6. Display all products with their inventory details.
SELECT
    p.product_name,
    i.stock_available,
    i.reorder_level
FROM inventory i
RIGHT JOIN products p
ON i.product_id = p.product_id;

-- Q7. Count the number of customers in each city.
SELECT 
	city, 
    COUNT(*) AS total_customers 
FROM customers GROUP BY city;

-- Q8. Count the number of products in each category.
SELECT
    c.category_name,
    COUNT(*) AS total_products
FROM products p
JOIN categories c
ON p.category_id = c.category_id
GROUP BY c.category_name;

-- Q9. Count the number of orders by order status.
SELECT
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;

-- Q10. Calculate the total revenue generated by each customer.
SELECT
    customer_id,
    SUM(total_amount) AS total_spent
FROM orders
GROUP BY customer_id
ORDER BY total_spent DESC;

-- Q11. Display customers whose total spending exceeds ₹1,00,000.
SELECT
    customer_id,
    SUM(total_amount) AS total_spent
FROM orders
GROUP BY customer_id
HAVING SUM(total_amount) > 100000;

-- Q12. Display categories with more than 10 products.
SELECT
    category_id,
    COUNT(*) AS total_products
FROM products
GROUP BY category_id
HAVING COUNT(*) > 10;

-- Q13. Display all unique product brands.
SELECT DISTINCT brand FROM products;

-- Q14. Display all unique customer cities.
SELECT DISTINCT city FROM customers;

-- Q15. Categorize products based on their price range.
SELECT
    product_name,
    price,
    CASE
        WHEN price < 1000 THEN 'Budget'
        WHEN price BETWEEN 1000 AND 10000 THEN 'Mid Range'
        ELSE 'Premium'
    END AS price_category
FROM products;

-- Q16. Categorize customers based on customer type.
SELECT
    first_name,
    last_name,
    customer_type,
    CASE
        WHEN customer_type='Premium' THEN 'Priority Customer'
        ELSE 'Regular Customer'
    END AS customer_category
FROM customers;

-- Q17. Display customer, product, and order details.
SELECT
    o.order_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    p.product_name,
    oi.quantity
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id;

-- Q18. Display payment details along with customer names.
SELECT
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    pay.payment_method,
    pay.payment_status,
    o.total_amount
FROM payments pay
JOIN orders o
ON pay.order_id = o.order_id
JOIN customers c
ON o.customer_id = c.customer_id;

-- Q19. Display shipping details along with customer names.
SELECT
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    s.courier_name,
    s.shipping_status
FROM shipping s
JOIN orders o
ON s.order_id = o.order_id
JOIN customers c
ON o.customer_id = c.customer_id;

-- Q20. Calculate the average rating of each product.
SELECT
    product_id,
    ROUND(AVG(rating),2) AS average_rating
FROM reviews
GROUP BY product_id
ORDER BY average_rating DESC;

-- Q21. Calculate the total stock available in inventory.
SELECT
    SUM(stock_available) AS total_stock
FROM inventory;

-- Q22. Calculate the average stock available by warehouse.
SELECT
    warehouse_location,
    ROUND(AVG(stock_available),2) AS average_stock
FROM inventory
GROUP BY warehouse_location;

-- Q23. Calculate the total quantity sold for each product.
SELECT
    product_id,
    SUM(quantity) AS total_quantity
FROM order_items
GROUP BY product_id
ORDER BY total_quantity DESC;

-- Q24. Count the number of products for each seller.
SELECT
    seller_id,
    COUNT(*) AS total_products
FROM products
GROUP BY seller_id
ORDER BY total_products DESC;

-- Q25. Count the total number of orders placed by each customer.
SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
ORDER BY total_orders DESC;
