-- 1. Products priced above average price.
SELECT product_id, product_name, price
FROM products
WHERE price >
(
    SELECT AVG(price) FROM products
);

-- 2. Customers who have placed more than the average number of orders.
SELECT customer_id, COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) >
(
    SELECT AVG(order_count) FROM
    (
        SELECT COUNT(*) AS order_count FROM orders
        GROUP BY customer_id
    ) t
);

-- 3. Products with the highest price.
SELECT * FROM products
WHERE price =
(
    SELECT MAX(price) FROM products
);

-- 4. Customers who have never placed an order.
SELECT *
FROM customers
WHERE customer_id NOT IN
(
    SELECT DISTINCT customer_id FROM orders
);

-- 5. Categories having more products than the average category.
SELECT category_id, COUNT(*) AS total_products
FROM products
GROUP BY category_id
HAVING COUNT(*) >
(
    SELECT AVG(product_count) FROM
    (
        SELECT COUNT(*) AS product_count
        FROM products
        GROUP BY category_id
    ) x
);

-- 6. Customers who have placed at least one order.
SELECT *
FROM customers c
WHERE EXISTS
(
    SELECT 1 FROM orders o
    WHERE o.customer_id = c.customer_id
);

-- 7. Products that have received at least one review.
SELECT *
FROM products p
WHERE EXISTS
(
    SELECT 1 FROM reviews r
    WHERE r.product_id = p.product_id
);

-- 8. Total spending of each customer.
WITH customer_spending AS
(
SELECT
customer_id,
SUM(total_amount) total_spent
FROM orders
GROUP BY customer_id
)

SELECT *
FROM customer_spending
ORDER BY total_spent DESC;

-- 9. Monthly revenue using CTE.
WITH monthly_sales AS
(
SELECT
YEAR(order_date) year,
MONTH(order_date) month,
SUM(total_amount) revenue
FROM orders
GROUP BY YEAR(order_date),MONTH(order_date)
ORDER BY YEAR(order_date)
)

SELECT *
FROM monthly_sales;

-- 10. Rank products by price.
SELECT 
	product_name, 
    price, 
	rank() OVER(ORDER BY price DESC) product_rank
FROM products;

-- 11. Dense Rank products.
SELECT
product_name,
price,
DENSE_RANK() OVER(ORDER BY price DESC) denserank
FROM products;

-- 12. Row Number.
SELECT
product_name,
price,
ROW_NUMBER() OVER(ORDER BY price DESC) row_num
FROM products;

-- 13. Top 3 expensive products.
SELECT product_name, price FROM products 
ORDER BY price DESC limit 3;

				-- OR
                
SELECT 
	product_name,
    price,
	RANK() OVER(ORDER BY price DESC) as Expensive_product
FROM products LIMIT 3;

-- 14. Highest selling product in each category.
SELECT *
FROM
(
SELECT
c.category_name,
p.product_name,
SUM(oi.quantity) qty,
RANK() OVER(
	PARTITION BY c.category_name
	ORDER BY SUM(oi.quantity) DESC
) rnk
FROM categories c
JOIN products p
ON c.category_id=p.category_id
JOIN order_items oi
ON p.product_id=oi.product_id
GROUP BY c.category_name,p.product_name
)t
WHERE rnk=1;

-- 15. Previous month's revenue.
SELECT
	DATE_FORMAT(order_date,'%Y-%m') month,
	SUM(total_amount) revenue,
	LAG(SUM(total_amount))
		OVER(ORDER BY DATE_FORMAT(order_date,'%Y-%m')) previous_month
FROM orders
GROUP BY DATE_FORMAT(order_date,'%Y-%m');

-- 16. Next month's revenue.
SELECT
	DATE_FORMAT(order_date,'%Y-%m') month,
	SUM(total_amount) revenue,
	LEAD(SUM(total_amount))
		OVER(ORDER BY DATE_FORMAT(order_date,'%Y-%m')) next_month
FROM orders
GROUP BY DATE_FORMAT(order_date,'%Y-%m');

-- 17. Customers whose spending is above their city's average.
SELECT *
FROM customers c
WHERE EXISTS
(
SELECT 1
FROM orders o
WHERE o.customer_id=c.customer_id
);

-- 18. Products priced above the average of their category.
SELECT
p1.product_name,
p1.price
FROM products p1
WHERE p1.price >
(
SELECT AVG(p2.price)
FROM products p2
WHERE p2.category_id=p1.category_id
);

-- 19. Running total revenue.
SELECT
order_date,
SUM(total_amount) revenue,
SUM(SUM(total_amount))
	OVER(ORDER BY order_date) running_total
FROM orders
GROUP BY order_date;

-- 20. Average order amount by month.
SELECT
MONTHNAME(order_date) month,
ROUND(AVG(total_amount),2) avg_order
FROM orders
GROUP BY MONTH(order_date),MONTHNAME(order_date);

-- 21. Top 5 customers using DENSE_RANK.
select customer_id,
sum(total_amount) spending,
DENSE_RANK()
	OVER(ORDER BY SUM(total_amount) DESC) spending_rank
FROM orders
GROUP BY customer_id limit 5;

-- 22. Seller with maximum products.
SELECT * FROM sellers WHERE seller_id=
(
	SELECT seller_id
	FROM products
	GROUP BY seller_id
	ORDER BY COUNT(*) DESC
	LIMIT 1
);

-- 23. Highest rated products.
SELECT
product_id,
ROUND(AVG(rating),2) avg_rating
FROM reviews
GROUP BY product_id
ORDER BY avg_rating DESC;

-- 24. Revenue generated by each seller.
SELECT
s.seller_name,
SUM(oi.quantity*oi.unit_price) revenue
FROM sellers s
JOIN products p
ON s.seller_id=p.seller_id
JOIN order_items oi
ON p.product_id=oi.product_id
GROUP BY s.seller_name
ORDER BY revenue DESC;

-- 25. Customer with maximum lifetime value.
SELECT
c.customer_id,
CONCAT(c.first_name,' ',c.last_name) customer_name,
SUM(o.total_amount) lifetime_value
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
GROUP BY c.customer_id,customer_name
ORDER BY lifetime_value DESC
LIMIT 1;